"""Exposure dashboard module.

This module contains the Plotly Dash application used to visualize script
exposure results generated by the exposure research pipeline.

The dashboard is intentionally separated from data preparation logic so the
pipeline entrypoint can remain focused on stage orchestration.
"""

from pathlib import Path

import pandas as pd
import plotly.express as px
from plotly.express.colors import qualitative
from plotly.graph_objs import Figure
from dash import Dash, dcc, html, Input, Output, ALL
from dash import callback_context, State

try:
    from paths import EXPOSURE_DATA_DIR
except ImportError:
    # Fallback for direct execution
    REPO_ROOT = Path(__file__).resolve().parent.parent
    DATA_ROOT = REPO_ROOT / "data"
    EXPOSURE_DATA_DIR = DATA_ROOT / "exposure"
EXPOSURE_DATA_PATH = EXPOSURE_DATA_DIR / "exposure_treemap_data.csv"
DEFAULT_COLOR_PALETTE = qualitative.Pastel


def load_exposure_data(path: str | Path = None) -> pd.DataFrame:
    """Load the exposure dashboard dataset from disk or URL."""
    if path is None:
        # Try local path first
        path = EXPOSURE_DATA_PATH

    if isinstance(path, str) and (path.startswith('http://') or path.startswith('https://')):
        # Load from URL
        df = pd.read_csv(path)
    else:
        # Load from local path
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(
                f"Missing exposure dashboard data: {path}."
                " Run the exposure pipeline in `exposure_research/main.py` first."
            )
        df = pd.read_csv(path)

    if "script" not in df.columns or "font_name" not in df.columns or "font_count" not in df.columns:
        raise ValueError(
            f"Exposure data must contain script, font_name, and font_count columns."
        )
    return df


def build_scripts_list(df: pd.DataFrame) -> list[str]:
    """Return scripts sorted by total font count."""
    return df["script"].value_counts().index.tolist()


def build_script_colors(scripts_list: list[str]) -> dict[str, str]:
    """Assign a color to each script from the default palette."""
    return {
        script: DEFAULT_COLOR_PALETTE[i % len(DEFAULT_COLOR_PALETTE)]
        for i, script in enumerate(scripts_list)
    }


def create_treemap(df: pd.DataFrame, script_colors: dict[str, str]) -> Figure:
    """Create a treemap visualization of font usage by supported scripts. (size of box = number of web requests)"""
    fig = px.treemap(
        df,
        path=["script", "font_name"],
        values="font_count",
        color="script",
        color_discrete_map=script_colors,
        title="Font Usage by Supported Scripts"
    )
    fig.update_layout(
        transition=dict(duration=0),
        margin=dict(t=50, l=10, r=10, b=10),
        autosize=True,
    )
    return fig


def run_exposure_dashboard(
    font_script_df: pd.DataFrame,
    scripts_list: list[str],
    script_colors: dict[str, str],
) -> Dash:
    """Create and return the exposure dashboard app."""
    app = Dash(__name__)

    app.layout = html.Div([
        html.H1("Script Exposure based on font requests"),
        html.Div([
            html.Label("Toggle Scripts:"),
            html.Div([
                html.Button(
                    script.capitalize(),
                    id={"type": "script-button", "index": script},
                    n_clicks=0,
                    style={
                        "margin": "5px",
                        "padding": "10px 15px",
                        "backgroundColor": "#1f77b4",
                        "color": "black",
                        "border": "none",
                        "borderRadius": "5px",
                        "cursor": "pointer",
                        "fontWeight": "bold"
                    }
                )
                for script in scripts_list
            ], style={"display": "flex", "flexWrap": "wrap", "marginBottom": "20px"})
        ], style={"padding": "20px"}),
        dcc.Store(id="selected-scripts-store", data=scripts_list),
        dcc.Graph(
            id="treemap-graph",
            style={"height": "85vh", "width": "100%"},
            config={"responsive": True},
        )
    ], style={"width": "100%", "margin": "0", "padding": "0"})

    @app.callback(
        Output("selected-scripts-store", "data"),
        Input({"type": "script-button", "index": ALL}, "n_clicks"),
        State("selected-scripts-store", "data"),
        prevent_initial_call=True
    )
    def update_selected_scripts(n_clicks, current_selected):
        """Toggle the clicked script on/off, keeping others unchanged."""
        ctx = callback_context
        if not ctx.triggered or not current_selected:
            return scripts_list

        clicked_script = ctx.triggered_id["index"]
        if clicked_script in current_selected:
            return [s for s in current_selected if s != clicked_script]
        return current_selected + [clicked_script]

    @app.callback(
        Output("treemap-graph", "figure"),
        Input("selected-scripts-store", "data")
    )
    def update_treemap(selected_scripts):
        """Update treemap based on selected scripts."""
        if not selected_scripts:
            selected_scripts = scripts_list
        filtered_df = font_script_df[font_script_df["script"].isin(selected_scripts)]
        return create_treemap(filtered_df, script_colors)

    @app.callback(
        Output({"type": "script-button", "index": ALL}, "style"),
        Input("selected-scripts-store", "data")
    )
    def update_button_styles(selected_scripts):
        """Update button appearance based on selection state."""
        return [
            {
                "margin": "5px",
                "padding": "10px 15px",
                "backgroundColor": script_colors[script] if script in selected_scripts else "#cccccc",
                "color": "black",
                "border": "none",
                "borderRadius": "5px",
                "cursor": "pointer",
                "fontWeight": "bold"
            }
            for script in scripts_list
        ]

    return app


def main() -> None:
    font_script_df = load_exposure_data()
    scripts_list = build_scripts_list(font_script_df)
    script_colors = build_script_colors(scripts_list)
    app = run_exposure_dashboard(font_script_df, scripts_list, script_colors)
    print("Starting Dash app on http://localhost:8050")
    app.run(debug=True)


# Module-level app for Plotly Cloud
try:
    # Try local first, fallback to remote URL for cloud deployment
    try:
        _font_script_df = load_exposure_data()
    except FileNotFoundError:
        # Load from remote URL (update this with your hosted CSV URL)
        remote_url = "https://raw.githubusercontent.com/Aditya-Khadye/TheScriptGap/refs/heads/main/data/exposure/exposure_treemap_data.csv"
        _font_script_df = load_exposure_data(remote_url)
    
    _scripts_list = build_scripts_list(_font_script_df)
    _script_colors = build_script_colors(_scripts_list)
    app = run_exposure_dashboard(_font_script_df, _scripts_list, _script_colors)
except Exception as e:
    # Fallback: create empty app if data isn't available
    app = Dash(__name__)
    app.layout = html.Div([
        html.H1("Exposure Dashboard"),
        html.P(f"Error loading data: {str(e)}")
    ])


if __name__ == "__main__":
    main()
